sudo: false
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install --upgrade pip
  - pip install codecov
  - make develop
script:
  - make quality
  - make test
branches:
  only:
    - master
after_success:
  - pip install --upgrade codecov
  - codecov
